CREATE TABLE machines (
    machine_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    machine_name VARCHAR2(100) NOT NULL,
    machine_type VARCHAR2(100),
    installation_date DATE,

    CONSTRAINT pk_machines
    PRIMARY KEY (machine_id)
);


CREATE TABLE machine_sensor_data (
    reading_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    machine_id NUMBER NOT NULL,

    air_temperature NUMBER(10,2),
    process_temperature NUMBER(10,2),
    rotational_speed NUMBER(10,2),
    torque NUMBER(10,2),
    tool_wear NUMBER(10,2),

    reading_time TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_machine_sensor_data
    PRIMARY KEY (reading_id),

    CONSTRAINT fk_sensor_machine
    FOREIGN KEY (machine_id)
    REFERENCES machines(machine_id)
);


CREATE TABLE predictions (
    prediction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    machine_id NUMBER NOT NULL,

    prediction_result NUMBER(1) NOT NULL,

    prediction_time TIMESTAMP
    DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_predictions
    PRIMARY KEY (prediction_id),

    CONSTRAINT fk_prediction_machine
    FOREIGN KEY (machine_id)
    REFERENCES machines(machine_id),

    CONSTRAINT chk_prediction_result
    CHECK (prediction_result IN (0, 1))
);
